=== dwyl/learn-json-schema/schemas/schema/schema/coverageInfo.json
{
  "id": "coverageInfo.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/0",
  "description": "Details about the content of a raster(grid) resource.",
  "translation": {
    "ISO 19115-2": ["MI_Metadata > contentInfo"]
  },
  "required": ["coverageType"],
  "additionalProperties": true,
  "properties": {
    "coverageType": {
      "type": "string",
      "description": "Type of information represented by the cell values",
      "translation": {
        "ISO 19115-2": ["MI_ImageDescription | MI_CoverageDescription > contentType"]
      }
    },
    "coverageName": {
      "type": "string",
      "description": "The name(title) of the coverage.",
      "translation": {
        "ISO 19115-2": ["MI_ImageDescription | MI_CoverageDescription > attributeDescription > gco:RecordType"]
      }
    },
    "coverageDescription": {
      "type": "string",
      "description": "A description of the coverage",
      "translation": {
        "ISO 19115-2": ["MI_ImageDescription | MI_CoverageDescription > attributeDescription > gco:RecordType"]
      }
    },
    "processingLevel": {
      "description": "Code that identifies the level of radiometric and geometric processing that has been applied.",
      "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/0/processingLevel",
      "translation": {
        "ISO 19115-2": ["MI_ImageDescription > processingLevelCode > RS_Identifier"]
      },
      "$ref": "citation.json#/definitions/identifier"
    },
    "coverageItem": {
      "type": "array",
      "description": "Information about the item(s) described by the grid cell.",
      "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/1",
      "translation": {
        "ISO 19115-2": ["MI_CoverageDescription > [gmi:rangeElementDescription | gmd:dimension]"]
      },
      "items": {
        "type": "object",
        "description": "Information about an item described by the grid cell.",
        "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/1",
        "properties": {
          "itemName": {
            "type": "string",
            "description": "Coverage item name.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription > gmi:name", "MI_CoverageDescription >  gmd:dimension > gmd:MD:Band > gmd:sequenceIdentifier > gco:MemberName > gco:aName"]
            }
          },
          "itemType": {
            "type": "string",
            "description": "The type of value for the coverage item.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD:Band > gmd:sequenceIdentifier > gco:MemberName > gco:attributeType > gco:TypeName > gco:aName"]
            }
          },
          "itemDescription": {
            "type": "string",
            "description": "Description of the coverage item.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription > gmi:definition", "MI_CoverageDescription >  gmd:dimension > gmd:MD_Band > gmd:descriptor ]"]
            }
          },
          "minValue": {
            "type": "number",
            "description": "The minimum value of data values in the domain of the coverage item.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:minValue > gco:Real"]
            }
          },
          "maxValue": {
            "type": "number",
            "description": "The maximum value of data values in the domain of the coverage item",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:maxValue > gco:Real"]
            }
          },
          "units": {
            "type": "string",
            "description": "The units of data in which the coverage item is expressed.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:units > gml:unitDefinition > gml:identifier"]
            }
          },
          "scaleFactor": {
            "type": "number",
            "description": "The scale factor which has been applied to the coverage item",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:scaleFactor > gco:Real"]
            }
          },
          "offset": {
            "type": "number",
            "description": "The physical value corresponding to a coverage item value of zero.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:offset > gco:Real"]
            }
          },
          "meanValue": {
            "type": "number",
            "description": "The mean value of data values in the coverage item."
          },
          "standardDeviation": {
            "type": "number",
            "description": "The standard deviation of data values in the coverage item."
          },
          "bitsPerValue": {
            "type": "integer",
            "description": "The maximum number of significant bits in the uncompressed representation for the value in each pixel.",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:bitsPerValue > gco:Integer"]
            }
          },
          "classifiedData": {
            "type": "object",
            "description": "The information about the thematic classification used with this coverage item.",
            "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/1",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription"]
            } ,
            "properties": {
              "numberOfClasses": {
                "type": "integer",
                "description": "The number of values used in a thematic classification resource."
              },
              "classifiedDataItem": {
                "type": "array",
                "description": "Information about thematic classification item(s).",
                "translation": {
                  "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription > gmi:rangeElement"]
                } ,
                "items": {
                  "type": "object",
                  "description": "Information about a thematic classification item.",
                  "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/1",
                  "properties": {
                    "className": {
                      "type": "string",
                      "description": "The name of the thematic classification item.",
                      "translation": {
                        "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription > gmi:rangeElement  > gco:Record > gmd:RS_Identifier > gmd:authority > gmd:CI_Citation > gmd:title"]
                      }
                    },
                    "classDescription": {
                      "type": "string",
                      "description": "The description of the thematic classification item.",
                      "translation": {
                        "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription > gmi:rangeElement  > gco:Record > gmd:RS_Identifier > gmd:authority > gmd:CI_Citation > gmd:alternateTitle"]
                      }
                    },
                    "classValue": {
                      "type": "number",
                      "description": "The thematic classification value.",
                      "translation": {
                        "ISO 19115-2": ["MI_CoverageDescription >  gmi:rangeElementDescription > gmi:MI_RangeElementDescription > gmi:rangeElement  > gco:Record > gmd:RS_Identifier > gmd:code"]
                      }
                    }
                  }
                }
              }
            }
          },
          "sensorInfo": {
            "type": "object",
            "description": "Information about the sensor that collected the grid cell values.",
            "example": "../../examples/full_example.json#/metadata/resourceInfo/coverageInfo/3",
            "translation": {
              "ISO 19115-2": ["MI_CoverageDescription > gmi:rangeElementDescription | gmd:dimension"]
            } ,
            "properties": {
              "toneGradations": {
                "type": "integer",
                "description": "The number of discrete numerical values in the grid data.",
                "translation": {
                  "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:toneGradition > gco:Integer"]
                }
              },
              "sensorMin": {
                "type": "number",
                "description": "The shortest wavelength that the sensor is capable of collecting within a designated band."
              },
              "sensorMax": {
                "type": "number",
                "description": "The longest wavelength that the sensor is capable of collecting within a designated band."
              },
              "sensorUnits": {
                "type": "string",
                "description": "The unit in which sensor wavelengths are expressed."
              },
              "sensorPeakResponse": {
                "type": "number",
                "description": "The wavelength at which the sensor response is highest.",
                "translation": {
                  "ISO 19115-2": ["MI_CoverageDescription > gmd:dimension > gmd:MD_Band > gmd:peakResponse > gco:Real"]
                }
              }
            }
          }
        }
      }
    },
    "imageInfo": {
      "type": "object",
      "description": "Information about the image.",
      "translation": {
        "ISO 19115-2": ["MI_ImageDescription"]
      },
      "required": [],
      "additionalProperties": true,
      "properties": {
        "illuminationElevationAngle": {
          "type": "number",
          "description": "Illumination elevation measured in degrees clockwise from the target plane at intersection of the optical line of sight with the Earth’s surface. For images from a scanning device, refer to the centre pixel of the image.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > illiminationElevationAngle"]
          }
        },
        "illuminationAzimuthAngle": {
          "type": "number",
          "description": "Illumination azimuth measured in degrees clockwise from true north at the time the image is taken. For images from a scanning device, refer to the centre pixel of the image",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > illuminationAzimuthAngle"]
          }
        },
        "imagingCondition": {
          "type": "string",
          "description": "Code which indicates conditions which may affect the image.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > imageCondition > MD_ImageConditionCode"]
          }
        },
        "imageQuality": {
          "description": "Specifies the image quality.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > imageQualityCode > RS_Identifier"]
          },
          "$ref": "citation.json#/definitions/identifier"
        },
        "cloudCoverPercent": {
          "type": "number",
          "maximum": 100,
          "description": "Area of the dataset obscured by clouds, expressed as a percentage of the spatial extent.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > cloudCoverPercentage"]
          }
        },
        "compressionQuantity": {
          "type": "number",
          "description": "Count of the number of lossy compression cycles performed on the image.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > compressionGenerationQuality"]
          }
        },
        "triangulationIndicator": {
          "type": "boolean",
          "description": "Indication of whether or not triangulation has been performed upon the image.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > triangulationIndicator"]
          }
        },
        "radiometricCalibrationAvailable": {
          "type": "boolean",
          "description": "Indication of whether or not the radiometric calibration information for generating the radiometrically calibrated standard data product is available.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > radiometricCalibrationDataAvailability"]
          }
        },
        "cameraCalibrationAvailable": {
          "type": "boolean",
          "description": "Indication of whether or not constants are available which allow for camera calibration corrections.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > camerCalibrationInformationAvailability"]
          }
        },
        "filmDistortionAvailable": {
          "type": "boolean",
          "description": "Indication of whether or not Calibration Reseau information is available",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > filmDistrotionInformationAvailability"]
          }
        },
        "lensDistortionAvailable": {
          "type": "boolean",
          "description": "Indication of whether or not lens aberration correction information is available.",
          "translation": {
            "ISO 19115-2": ["MI_ImageDescription > lensDistortionInformationAvailability"]
          }
        }
      }
    }
  }
}

=== dwyl/learn-json-schema/schemas/examples/coverageInfo.json
[
  {
    "coverageType": "coverageType",
    "coverageName": "coverageName",
    "coverageDescription": "coverageDescription",
    "processingLevel": {
      "identifier": "identifier",
      "type": "type",
      "namespace": "namespace",
      "version": "version",
      "description": "description",
      "authority": {
        "title": "title",
        "alternateTitle": "alternateTitle",
        "date": [
          {
            "date": "1111-11-11",
            "dateType": "dateType1"
          }
        ],
        "responsibleParty": [
          {
            "contactId": "contactId1",
            "role": "role1"
          }
        ],
        "onlineResource": [
          {
            "uri": "http://thisisanexample1.com",
            "protocol": "protocol1",
            "name": "name1",
            "description": "description1",
            "function": "function1"
          }
        ]
      }
    },
    "coverageItem": [
      {
        "itemName": "itemName1",
        "itemType": "itemType1",
        "itemDescription": "itemDescription1",
        "minValue": 111.11,
        "maxValue": 111.11,
        "units": "",
        "scaleFactor": 111.11,
        "offset": 111.11,
        "meanValue": 111.11,
        "standardDeviation": 111.119,
        "bitsPerValue": 1,
        "classifiedData": {
          "numberOfClasses": 1,
          "classifiedDataItem": [
            {
              "className": "className11",
              "classDescription": "classDescription11",
              "classValue": 111.11
            }, {
              "className": "className12",
              "classDescription": "classDescription12",
              "classValue": 222.22
            }
          ]
        },
        "sensorInfo": {
          "toneGradations": 1,
          "sensorMin": 111.11,
          "sensorMax": 111.11,
          "sensorUnits": "sensorUnits1",
          "sensorPeakResponse": 111.11
        }
      }, {
        "itemName": "itemName2",
        "itemType": "itemType2",
        "itemDescription": "itemDescription2",
        "minValue": 222.22,
        "maxValue": 222.22,
        "units": "",
        "scaleFactor": 222.22,
        "offset": 222.22,
        "meanValue": 222.22,
        "standardDeviation": 222.22,
        "bitsPerValue": 2,
        "classifiedData": {
          "numberOfClasses": 2,
          "classifiedDataItem": [
            {
              "className": "className21",
              "classDescription": "classDescription21",
              "classValue": 222.22
            }
          ]
        },
        "sensorInfo": {
          "toneGradations": 2,
          "sensorMin": 222.22,
          "sensorMax": 222.22,
          "sensorUnits": "sensorUnits2",
          "sensorPeakResponse": 222.22
        }
      }
    ],
    "imageInfo": {
      "illuminationElevationAngle": 111.11,
      "illuminationAzimuthAngle": 111.11,
      "imagingCondition": "imagingCondition",
      "imageQuality": {
        "identifier": "identifier",
        "type": "type",
        "namespace": "namespace",
        "version": "version",
        "description": "description",
        "authority": {
          "title": "title",
          "alternateTitle": "alternateTitle",
          "date": [
            {
              "date": "1111-11-11",
              "dateType": "dateType1"
            }
          ],
          "responsibleParty": [
            {
              "contactId": "contactId1",
              "role": "role1"
            }
          ],
          "onlineResource": [
            {
              "uri": "http://thisisanexample1.com",
              "protocol": "protocol1",
              "name": "name1",
              "description": "description1",
              "function": "function1"
            }
          ]
        }
      },
      "cloudCoverPercent": 11.11,
      "compressionQuantity": 1,
      "triangulationIndicator": true,
      "radiometricCalibrationAvailable": true,
      "cameraCalibrationAvailable": true,
      "filmDistortionAvailable": true,
      "lensDistortionAvailable": true
    }
  }
]
