=== dwyl/learn-json-schema/schemas/schema/schema/extent.json
{
  "id": "extent.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Information about the geographic, vertical, and temporal extent of a resource.",
  "example": "../../examples/full_example.json#/metadata/resourceInfo/extent",
  "translation": {
    "ISO 19115-2": ["EX_Extent"]
  },
  "additionalProperties": true,
  "properties": {
    "description": {
      "type": "string",
      "description": "Description of the geographic extent.",
      "translation": {
        "ISO 19115-2": ["EX_Extent > description"]
      }
    },
    "geographicElement": {
      "type": "array",
      "description": "An array of objects each describing a geographic boundary or location comprising all or a portion of the resource.",
      "translation": {
        "ISO 19115-2": ["EX_Extent > geographicElement"]
      },
      "items": {
        "type": "object",
        "example": "../../examples/full_example.json#/metadata/resourceInfo/extent/0/geographicElement",
        "properties": {
          "type": {
            "enum": ["Feature", "FeatureCollection", "GeometryCollection", "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon"],
            "description": "The type of geographic object."
          }
        },
        "oneOf": [
          {
            "$ref": "geojson/geojson.json#"
          }
        ]
      }
    },
    "verticalElement": {
      "type": "array",
      "description": "An array of objects each describing a vertical boundary comprising all or a portion of the resource.",
      "translation": {
        "ISO 19115-2": ["EX_Extent > verticalElement > EX_VerticalExtent "]
      },
      "items": {
        "$ref": "#/definitions/verticalExtent"
      }
    },
    "temporalElement": {
      "$ref": "#/definitions/temporalElement",
      "description": "An array of objects each describing a temporal boundary comprising all or a portion of the resource."
    }
  },
  "definitions": {
    "timeInstant": {
      "type": "object",
      "example": "../../examples/full_example.json#/metadata/resourceInfo/extent/0/temporalElement/timeInstant/0",
      "required": ["timePosition"],
      "additionalProperties": true,
      "properties": {
        "id": {
          "type": "string",
          "description": "A unique identifier for the timeInstant.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimeInstant @id"]
          }
        },
        "description": {
          "type": "string",
          "description": "A brief description providing relevant information about the date and time.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimeInstant > description"]
          }
        },
        "timePosition": {
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimeInstant > timePosition"]
          },
          "$ref": "../schema.json#/definitions/date"
        }
      }
    },
    "timePeriod": {
      "type": "object",
      "description": "A span of time represented by a starting date-time and an ending date-time.",
      "example": "../../examples/full_example.json#/metadata/resourceInfo/extent/0/temporalElement/timePeriod/0",
      "additionalProperties": true,
      "properties": {
        "id": {
          "type": "string",
          "description": "A unique identifier for a time period.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimePeriod @id"]
          }
        },
        "description": {
          "type": "string",
          "description": "A brief description providing relevant information about the time period.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimePeriod > description "]
          }
        },
        "beginPosition": {
          "description": "Starting date, or date and time.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimePeriod > beginPosition "],
            "FGDC CSDGM": ["idinfo > timeperd > rngdates > begdate"]
          },
          "$ref": "../schema.json#/definitions/date"
        },
        "endPosition": {
          "description": "Ending date, or date and time.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimePeriod > endPosition"],
            "FGDC CSDGM": ["idinfo > timeperd > rngdates > enddate"]
          },
          "$ref": "../schema.json#/definitions/date"
        }
      },
      "anyOf": [
        {
          "title": "beginPosition required",
          "required": ["beginPosition"]
        }, {
          "title": "endPosition required",
          "required": ["endPosition"]
        }
      ]
    },
    "temporalElement": {
      "type": "object",
      "description": "Temporal context for the resource.",
      "example": "../../examples/full_example.json#/metadata/resourceInfo/extent/0/temporalElement",
      "translation": {
        "ISO 19115-2": ["EX_Extent > temporalElement > EX_TemporalExtent"]
      },
      "additionalProperties": true,
      "minProperties": 1,
      "properties": {
        "timeInstant": {
          "type": "array",
          "description": "A set of date-time instances, each with an associated identifier and description.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimeInstant"]
          },
          "items": {
            "$ref": "#/definitions/timeInstant"
          }
        },
        "timePeriod": {
          "type": "array",
          "description": "A set of time periods(a span of time represented by a starting date-time and an ending date-time).",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimePeriod"]
          },
          "items": {
            "$ref": "#/definitions/timePeriod"
          }
        },
        "date": {
          "type": "array",
          "description": "A set of date-times.",
          "translation": {
            "ISO 19115-2": ["EX_TemporalExtent > extent > TimeInstant > timePosition"]
          },
          "items": {
            "$ref": "../schema.json#/definitions/date"
          }
        }
      }
    },
    "verticalExtent": {
      "type": "object",
      "description": "Vertical element of an extent.",
      "translation": {
        "ISO 19115-2": ["EX_Extent > verticalElement > EX_VerticalExtent "]
      },
      "additionalProperties": true,
      "required": ["minimumValue", "maximumValue", "verticalCRSTitle", "verticalCRSUri"],
      "properties": {
        "minimumValue": {
          "type": "number",
          "description": "Lowest vertical extent contained in the dataset.",
          "translation": {
            "ISO 19115-2": ["EX_VerticalExtent > minimumValue > Real "]
          }
        },
        "maximumValue": {
          "type": "number",
          "description": "Highest vertical extent contained in the dataset.",
          "translation": {
            "ISO 19115-2": ["EX_VerticalExtent > maximumValue > Real "]
          }
        },
        "verticalCRSTitle": {
          "type": "string",
          "description": "Name of a geographic reference system associated with a vertical extent.",
          "translation": {
            "ISO 19115-2": ["EX_VerticalExtent > verticalCRS @xlink:title "],
            "FGDC CSDGM": ["spref > vertdef > altsys > altdatum"]
          }
        },
        "verticalCRSUri": {
          "description": "Web link to the parameters for a geographic reference system associated with a vertical extent.",
          "translation": {
            "ISO 19115-2": ["EX_VerticalExtent > verticalCRS @xlink:href "]
          },
          "$ref": "../schema.json#/definitions/uri"
        }
      }
    }
  }
}

=== dwyl/learn-json-schema/schemas/examples/extent_polygon.json
[
  {
    "description":"BBOX only",
    "geographicElement":[
      {
        "type":"Feature",
        "bbox":[
          -148.1764,
          57.01428,
          -132.821,
          60.917
        ],
        "geometry":null,
        "properties":{
          "includesData":true,
          "description":"Gulf of Alaska"
        },
        "crs":{
          "type":"link",
          "properties":{
            "href":"http://spatialreference.org/ref/epsg/4326/proj4/",
            "type":"proj4"
          }
        }
      }
    ],
    "temporalElement":{
      "timeInstant":[
        {
          "id":"ti-001",
          "description":"ground condition",
          "timePosition":"2012-07-15T08:05:00.0+09:00"
        }
      ]
    },
    "verticalElement":[
      {
        "minimumValue":-500,
        "maximumValue":0,
        "verticalCRSTitle":"NAVD88 depth",
        "verticalCRSUri":"http://www.epsg-registry.org/export.htm?gml=urn:ogc:def:crs:EPSG::6357"
      }
    ]
  },
  {
    "description":"Polygon with BBOX",
    "geographicElement":[
      {
        "type":"Feature",
        "id":"unique1",
        "bbox":[
          -148.1764,
          57.01428,
          -132.821,
          60.917
        ],
        "geometry":{
          "type":"Polygon",
          "coordinates":[
            [
              [
                -139.388046,
                59.828561
              ],
              [
                -140.882186,
                59.839602
              ],
              [
                -143.101425,
                60.22375
              ],
              [
                -147.056503,
                60.829147
              ],
              [
                -148.902206,
                59.982807
              ],
              [
                -148.792343,
                57.944338
              ],
              [
                -134.576034,
                57.663361
              ]
            ]
          ]
        },
        "properties":{
          "includesData":true,
          "description":"Gulf of Alaska"
        },
        "crs":{
          "type":"name",
          "properties":{
            "name":"urn:ogc:def:crs:OGC:1.3:CRS84"
          }
        }
      },
      {
        "type":"Feature",
        "id":"unique101",
        "bbox":[
          -97.067240989074,
          18.556394455134,
          -80.807475364074,
          29.366941330134
        ],
        "geometry":{
          "type":"Polygon",
          "coordinates":[
            [
              [
                -84.059428489074,
                29.366941330134
              ],
              [
                -97.067240989074,
                28.048581955134
              ],
              [
                -95.397319114074,
                18.556394455134
              ],
              [
                -80.895365989074,
                24.620847580134
              ],
              [
                -80.807475364074,
                24.708738205134
              ],
              [
                -84.059428489074,
                29.366941330134
              ]
            ]
          ]
        },
        "properties":{
          "includesData":false,
          "description":"Gulf of Mexico",
          "text":"Whatever I want."
        },
        "crs":{
          "type":"name",
          "properties":{
            "name":"urn:ogc:def:crs:OGC:1.3:CRS84"
          }
        }
      }
    ],
    "temporalElement":{
      "timePeriod":[
        {
          "id":"tp-001",
          "description":"Ground Condition",
          "beginPosition":"1987-05-16T16:05:00",
          "endPosition":"2011-12"
        },
        {
          "id":"tp-101",
          "description":"Below Ground Condition",
          "beginPosition":"1987-08-13T16:05:00",
          "endPosition":"2012-12-12"
        }
      ]
    },
    "verticalElement":[
      {
        "minimumValue":0,
        "maximumValue":1000,
        "verticalCRSTitle":"NAVD88 height",
        "verticalCRSUri":"http://www.epsg-registry.org/export.htm?gml=urn:ogc:def:crs:EPSG::5703"
      },
      {
        "minimumValue":1500,
        "maximumValue":0,
        "verticalCRSTitle":"NAVD88 depth",
        "verticalCRSUri":"http://www.epsg-registry.org/export.htm?gml=urn:ogc:def:crs:EPSG::6357"
      }
    ]
  },
  {
    "description":"A feature collection with just polygons",
    "geographicElement":[
      {
        "type":"FeatureCollection",
        "id":"unique2",
        "bbox":[
          -149.89603182812,
          61.215716023773,
          -149.87405917187,
          61.225371976227
        ],
        "properties":{
          "name":"A FeatureCollection(polygons)",
          "description":"represents GML MultiGeometry",
          "includesData":true
        },
        "crs":{
          "type":"name",
          "properties":{
            "name":"urn:ogc:def:crs:OGC:1.3:CRS84"
          }
        },
        "features":[
          {
            "type":"Feature",
            "id":"unique3",
            "geometry":{
              "type":"Polygon",
              "coordinates":[
                [
                  [
                    -149.880796,
                    61.21988
                  ],
                  [
                    -149.880625,
                    61.221305
                  ],
                  [
                    -149.889386,
                    61.221346
                  ],
                  [
                    -149.880796,
                    61.21988
                  ]
                ],
                [
                  [
                    -149.8807,
                    61.21990
                  ],
                  [
                    -149.880627,
                    61.221300
                  ],
                  [
                    -149.8809,
                    61.221300
                  ],
                  [
                    -149.8807,
                    61.21990
                  ]
                ],
                [
                  [
                    -149.889300,
                    61.221300
                  ],
                  [
                    -149.889382,
                    61.221345
                  ],
                  [
                    -149.889382,
                    61.221445
                  ],
                  [
                    -149.889300,
                    61.221300
                  ]
                ]
              ]
            },
            "properties":{
              "name":"Buttress Park sampling location",
              "description":"Boundary of area in downtown Anchorage where sampling occurred"
            }
          },
          {
            "type":"Feature",
            "id":"unique4",
            "geometry":{
              "type":"Polygon",
              "coordinates":[
                [
                  [
                    -149.888221,
                    61.219643
                  ],
                  [
                    -149.889466,
                    61.219643
                  ],
                  [
                    -149.889251,
                    61.219973
                  ],
                  [
                    -149.887835,
                    61.219952
                  ],
                  [
                    -149.888221,
                    61.219643
                  ]
                ]
              ]
            },
            "properties":{
              "includesData":false,
              "name":"Equipment staging area",
              "description":"Area where sampling equipment was stored, no sampling occurred (Note:includesData should be ignored here. Would need to move this feature into another geographicElement.)"
            }
          }
        ]
      }
    ],
    "temporalElement":{
      "timePeriod":[
        {
          "id":"tp-002",
          "beginPosition":"2013-08-24T08:05:00",
          "endPosition":"2013-10-04"
        },
        {
          "id":"tp-004",
          "beginPosition":"2010-08-24T08:05:00",
          "endPosition":"2014-10-04",
          "description":"The best days of my life"
        }
      ],
      "timeInstant":[
        {
          "id":"ti-002",
          "description":"below ground condition",
          "timePosition":"2012-07-15T08:05:00.0+09:00"
        },
        {
          "id":"ti-003",
          "description":"below ground condition",
          "timePosition":"2012-08-16T08:06:00.0+09:00"
        }
      ]
    },
    "verticalElement":[
      {
        "minimumValue":60.5,
        "maximumValue":110.68,
        "verticalCRSTitle":"NAVD88 height (ftUS)",
        "verticalCRSUri":"http://www.epsg-registry.org/export.htm?gml=urn:ogc:def:axis-name:EPSG::9904"
      }
    ]
  }
]
