=== dwyl/learn-json-schema/schemas/schema/schema/gridInfo.json
{
  "id": "gridInfo.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "example": "../../examples/full_example.json#/metadata/resourceInfo/gridInfo/0",
  "description": "Information about grid objects in the resource.",
  "translation": {
    "ISO 19115-2": ["MD_GridSpatialRepresentation"]
  },
  "type": "object",
  "required": ["numberOfDimensions", "cellGeometry", "dimension"],
  "additionalProperties": true,
  "properties": {
    "numberOfDimensions": {
      "type": "number",
      "description": "The number of independent spatial-temporal axes.",
      "translation": {
        "ISO 19115-2": ["MD_GridSpatialRepresentation > numberOfDimensions"]
      }
    },
    "dimension": {
      "type": "array",
      "description": "Information about spatial-temporal axis properties.",
      "translation": {
        "ISO 19115-2": ["MD_GridSpatialRepresentation > axisDimensionProperties"]
      },
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/dimension"
      }
    },
    "cellGeometry": {
      "type": "string",
      "description": "Identification of grid data as point or cell.",
      "translation": {
        "ISO 19115-2": ["MD_GridSpatialRepresentation > cellGeometry"]
      }
    },
    "transformationParameterAvailability": {
      "type": "boolean",
      "description": "An indication of whether or not parameters for transformation between image coordinates and geographic or map coordinates exist (are available).",
      "translation": {
        "ISO 19115-2": ["MD_GridSpatialRepresentation > transformationParameterAvailability"]
      }
    }
  },
  "definitions": {
    "dimension": {
      "type": "object",
      "required": ["dimensionType", "dimensionSize"],
      "properties": {
        "dimensionType": {
          "type": "string",
          "description": "The type of dimension for this axis.",
          "translation": {
            "ISO 19115-2": ["MD_GridSpatialRepresentation > axisDimensionProperties > MD_Dimension > dimensionName > MD_DimensionNameTypeCode"]
          }
        },
        "dimensionSize": {
          "type": "integer",
          "description": "The number of elements along the axis.",
          "translation": {
            "ISO 19115-2": ["MD_GridSpatialRepresentation > axisDimensionProperties > MD_Dimension > dimensionSize"]
          }
        },
        "resolution": {
          "type": "number",
          "description": "Numeric Value that defines the degree of detail in the grid.",
          "translation": {
            "ISO 19115-2": ["MD_GridSpatialRepresentation > axisDimensionProperties > MD_Dimension > resolution"]
          }
        },
        "resolutionUnit": {
          "type": "string",
          "description": "Unit of measure for the resolution.",
          "translation": {
            "ISO 19115-2": ["MD_GridSpatialRepresentation > axisDimensionProperties > MD_Dimension > resolution @uom"]
          }
        },
        "dimensionTitle": {
          "type": "string",
          "description": "The name of the axis.",
          "translation": {
            "ISO 19115-2": [""]
          }
        },
        "dimensionDescription": {
          "type": "string",
          "description": "The description of the axis.",
          "translation": {
            "ISO 19115-2": [""]
          }
        }
      }
    }
  }
}

=== dwyl/learn-json-schema/schemas/examples/gridInfo.json
{
  "numberOfDimensions": 2,
  "dimension": [
    {
      "dimensionType": "column",
      "dimensionSize": 800,
      "resolution": 10,
      "resolutionUnit": "Meter",
      "dimensionTitle": "x-axis",
      "dimensionDescription": "The x-axis."
    },
    {
      "dimensionType": "row",
      "dimensionSize": 600,
      "resolution": 10,
      "resolutionUnit": "Meter",
      "dimensionTitle": "y-axis",
      "dimensionDescription": "The y-axis."
    }
  ],
  "cellGeometry": "area",
  "transformationParameterAvailability": false
}
