=== dwyl/learn-json-schema/schemas/schema/schema/resourceInfo.json
{
  "id": "resourceInfo.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Information about the resource.",
  "type": "object",
  "example": "../../examples/full_example.json#/metadata/resourceInfo",
  "translation": {
    "ISO 19115-2": ["MD_DataIdentification"],
    "FGDC CSDGM": ["idinfo"]
  },
  "required": ["resourceType", "citation", "abstract", "status", "language", "pointOfContact"],
  "additionalProperties": true,
  "properties": {
    "resourceType": {
      "type": "string",
      "description": "Identifies the type of resource, such as: a dataset, study, publication, etc.",
      "translation": {
        "ISO 19115-2": ["MI_Metadata > hierarchyLevel [MD_ScopeCode]"]
      }
    },
    "citation": {
      "description": "Citation for the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > citation > CI_Citation"],
        "FGDC CSDGM": ["idinfo > citation"]
      },
      "$ref": "citation.json#"
    },
    "resourceTimePeriod": {
      "description": "Time period for the resource, e.g. project start and end date(s).",
      "translation": {
        "ISO 19115-2": ["EX_Extent > temporalElement > EX_TemporalExtent > extent > TimePeriod"]
      },
      "$ref": "extent.json#/definitions/timePeriod"
    },
    "pointOfContact": {
      "type": "array",
      "description": "Identification of, and means of communication with, person(s) and organizations that may be contacted for acquiring knowledge about or acquisition of the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > pointOfContact"]
      },
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "contact.json#/definitions/contactRef"
      }
    },
    "abstract": {
      "type": "string",
      "description": "Brief narrative summary of the content of the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > abstract"],
        "FGDC CSDGM": ["idinfo > descript > abstract"]
      }
    },
    "shortAbstract": {
      "type": "string",
      "description": "A short description of the resource. Max of 300 characters."
    },
    "status": {
      "type": "string",
      "description": "Status of the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > status [MD_ProgressCode]"],
        "FGDC CSDGM": ["idinfo > status > progress"]
      }
    },
    "hasMapLocation": {
      "type": "boolean",
      "description": "A flag indicating that a resource has a geographic location associated with it and therefore can be located using a map interface."
    },
    "hasDataAvailable": {
      "type": "boolean",
      "description": "A flag to indicate whether data for this resource is available for distribution."
    },
    "language": {
      "type": "array",
      "deprecated": true,
      "description": "Language(s) used within the resource. Should be a valid ISO 639-3 code. NOTE:This property has been deprecated in favor of 'locale'.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > language"]
      },
      "items": {
        "type": "string"
      }
    },
    "characterSet": {
      "type": "array",
      "deprecated": true,
      "description": "Full name of the character encoding standard used by the resource. NOTE:This property has been deprecated in favor of 'locale'.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > characterSet [MD_CharacterSetCode]"]
      },
      "items": {
        "type": "string"
      }
    },
    "locale": {
      "type": "array",
      "description": "Localised language(s) and characterset(s) used within the resource.",
      "items": {
        "$ref": "locale.json"
      }
    },
    "purpose": {
      "type": "string",
      "description": "A summary of intentions for which the resource was created.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > purpose"],
        "FGDC CSDGM": ["idinfo > descript > purpose"]
      }
    },
    "credit": {
      "type": "array",
      "description": "A narrative identification of additional resources credited for the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > credit"],
        "FGDC CSDGM": ["idinfo > datacred"]
      },
      "items": {
        "type": "string"
      }
    },
    "topicCategory": {
      "type": "array",
      "description": "General theme keyword of the resource, such as: oceans, biota atmosphere, etc.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > topicCategory"]
      },
      "items": {
        "type": "string"
      }
    },
    "environmentDescription": {
      "type": "string",
      "description": "Description of the dataset in the producer's processing environment, including items such as the software, the computer, the computer operating system, file name, and the dataset size.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > environmentDescription"],
        "FGDC CSDGM": ["idinfo > native"]
      }
    },
    "resourceNativeFormat": {
      "type": "array",
      "description": "Provides a description of the format of the resource(s).",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > resourceFormat > MD_Format"]
      },
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "distributor.json#/definitions/format"
      }
    },
    "keyword": {
      "type": "array",
      "description": "Provides category keywords, their type, and reference source.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > descriptiveKeywords > MD_Keywords"],
        "FGDC CSDGM": ["idinfo > keywords"]
      },
      "uniqueItems": true,
      "items": {
        "$ref": "keyword.json"
      }
    },
    "resourceMaintenance": {
      "type": "array",
      "description": "Information about the maintenance of the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > resourceMaintenance > MD_MaintenanceInformation"]
      },
      "items": {
        "$ref": "maintInfo.json#"
      }
    },
    "resourceSpecificUsage": {
      "type": "array",
      "description": "Description of ways in which the resource is currently or has been used.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > resourceSpecificUsage > MD_Usage"]
      },
      "uniqueItems": true,
      "items": {
        "$ref": "usage.json"
      }
    },
    "graphicOverview": {
      "type": "array",
      "description": "Provides a path or link to images, maps, flow charts, models, etc. that illustrate the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > graphicOverview > MD_BrowseGraphic"]
      },
      "items": {
        "$ref": "graphicOverview.json#"
      }
    },
    "constraint": {
      "type": "object",
      "description": "Provides information about constraints to the use of the resource.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > resourceConstraints"]
      },
      "properties": {
        "useLimitation": {
          "type": "array",
          "description": "Limitation affecting the fitness for use of the resource or metadata. For example, \"not to be used for navigation\".",
          "example": "../../examples/full_example.json#/metadata/resourceInfo/constraint",
          "translation": {
            "ISO 19115-2": ["MD_DataIdentification > resourceConstraints > MD_Constraints[useLimitation]"]
          },
          "items": {
            "$ref": "resourceConstraint.json#/definitions/useLimitation"
          }
        },
        "legalConstraint": {
          "type": "array",
          "description": "Restrictions and legal prerequisites for accessing and using the resource or metadata.",
          "example": "../../examples/full_example.json#/metadata/resourceInfo/constraint/legalConstraint",
          "translation": {
            "ISO 19115-2": ["MI_Metadata > resourceConstraints > MD_LegalConstraints"]
          },
          "items": {
            "$ref": "resourceConstraint.json#/definitions/legalConstraint"
          }
        },
        "securityConstraint": {
          "type": "array",
          "description": "Handling restrictions imposed on the resource or metadata for national security or similar security concerns.",
          "example": "../../examples/full_example.json#/metadata/resourceInfo/constraint/securityConstraint",
          "translation": {
            "ISO 19115-2": ["MI_Metadata > resourceConstraints > MD_SecurityConstraints"]
          },
          "items": {
            "$ref": "resourceConstraint.json#/definitions/securityConstraint"
          }
        }
      }
    },
    "taxonomy": {
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > taxonomy"],
        "FGDC CSDGM": ["idinfo > taxonomy"]
      },
      "$ref": "taxonomy.json"
    },
    "spatialReferenceSystem": {
      "description": "Geospatial referencing system used in the the data resource. The reference can be provided by an EPSG number, a named reference, or providing the parameters in a well known text (WKT) format.",
      "example": "../../examples/spatialRef.json",
      "translation": {
        "ISO 19115-2": ["MD_Metadata > referenceSystemInfo > MD_ReferenceSystem > referenceSystemIdentifier > RS_Identifier > code"]
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "array",
          "description": "A recognized reference system name.",
          "items": {
            "type": "string"
          }
        },
        "epsgNumber": {
          "type": "array",
          "description": "The EPSG Geodetic Parameter Dataset of the reference system, see epsg-registry.org.",
          "items": {
            "type": "integer"
          }
        },
        "wkt": {
          "type": "array",
          "description": "Well-known text representation of the reference system.",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "spatialRepresentation": {
      "type": "array",
      "description": "Format of the resource geographic extent, such as: vector, grid, etc.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdenification > spatialRepresentationType [MD_SpatialRepresentationTypeCode]"],
        "FGDC CSDGM": ["spdoinfo"]
      },
      "items": {
        "type": "string"
      }
    },
    "spatialResolution": {
      "type": "array",
      "description": "Information about the scale of the geographic extent.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdenification > spatialResolution > MD_Resolution"]
      },
      "items": {
        "$ref": "resolution.json"
      }
    },
    "extent": {
      "type": "array",
      "description": "Information about the geographic, vertical, and temporal extent of the resource. A resource may have multiple extents.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > extent > EX_Extent"]
      },
      "items": {
        "$ref": "extent.json"
      }
    },
    "gridInfo": {
      "type": "array",
      "description": "Information about grid objects in the resource.",
      "translation": {
        "ISO 19115-2": ["MD_GridSpatialRepresentation"]
      },
      "items": {
        "$ref": "gridInfo.json"
      }
    },
    "coverageInfo": {
      "type": "array",
      "description": "Details about the content of a raster(grid) resource.",
      "translation": {
        "ISO 19115-2": ["MI_Metadata > contentInfo"]
      },
      "items": {
        "$ref": "coverageInfo.json"
      }
    },
    "dataQualityInfo": {
      "type": "array",
      "description": "Information that describes the data quality, lineage, and/or processing steps that were applied to the whole or part of the data resource.",
      "translation": {
        "ISO 19115-2": ["MI_Metadata > dataQualityInfo > DQ_DataQuality"],
        "FGDC CSDGM": ["dataqual"]
      },
      "items": {
        "$ref": "dataQuality.json#"
      }
    },
    "supplementalInfo": {
      "type": "string",
      "description": "Any other descriptive information about the dataset.",
      "translation": {
        "ISO 19115-2": ["MD_DataIdentification > supplementalInfo"]
      }
    }
  }
}

=== dwyl/learn-json-schema/schemas/examples/resourceInfo.json
[
  {
    "resourceType":"project",
    "citation":{
      "title":"Project Tracking System",
      "date":[
        {
          "date":"2013-03-13",
          "dateType":"creation"
        }
      ],
      "responsibleParty":[
        {
          "contactId":"1",
          "role":"originator"
        },
        {
          "contactId":"2",
          "role":"publisher"
        }
      ]
    },
    "resourceTimePeriod": {
      "description": "Span of project activity",
      "beginPosition": "2011-09-03",
      "endPosition": "2014-11-15"
    },
    "pointOfContact":[
      {
        "contactId":"1",
        "role":"custodian"
      }
    ],
    "abstract":"The Arctic LCC has developed a Project Tracking System(PTS) to assist with the management of projects. The PTS is used to track projects throughout all stages of development, from receipt of proposals through delivery of final products.",
    "status":"onGoing",
    "language":[
      "eng; USA"
    ],
    "resourceNativeFormat":[
      {
        "formatName":"ExtJS",
        "version":"4.0.7"
      },
      {
        "formatName":"PostgreSQL",
        "version":"9.1"
      },
      {
        "formatName":"PHP",
        "version":"5.3"
      }
    ],
    "keyword":[
      {
        "keyword":[
          "Oceans > Ocean temperature > Thermocline",
          "Oceans > Ocean Temperature > Water Temperature",
          "Oceans > Ocean Heat Budget > Heat Flux"
        ],
        "keywordType":"theme",
        "thesaurus":{
          "title":"NASA/Global Change Master Directory (GCMD) Earth Science Keywords.",
          "date":[
            {
              "date":"2013-09-19",
              "dateType":"revision"
            }
          ],
          "onlineResource":[
            {
              "uri":"http://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv"
            }
          ],
          "edition":"Version 8.0.0.0.0",
          "responsibleParty":[
            {
              "contactId":"1",
              "role":"originator"
            },
            {
              "contactId":"2",
              "role":"owner"
            }
          ],
          "presentationForm":[
            "documentDigital"
          ],
          "identifier":[
            {
              "type":"isbn",
              "identifier":"HB12365.214"
            },
            {
              "type":"issn",
              "identifier":"0ab4-dd983c01"
            }
          ]
        }
      }
    ]
  },
  {
    "resourceType":"project",
    "citation":{
      "title":"Project Tracking System",
      "date":[
        {
          "date":"2011-11-11",
          "dateType":"publication"
        },
        {
          "date":"2013-03-13T17:30-08:00",
          "dateType":"revision"
        }
      ],
      "edition":"version 1.2.0",
      "responsibleParty":[
        {
          "contactId":"1",
          "role":"originator"
        },
        {
          "contactId":"2",
          "role":"publisher"
        }
      ],
      "presentationForm":[
        "documentDigital"
      ],
      "additionalIdentifier":{
        "doi":"10.1000/182",
        "isbn":"HB12365.214",
        "issn":"0ab4-dd983c01"
      }
    },
    "pointOfContact":[
      {
        "contactId":"1",
        "role":"custodian"
      }
    ],
    "abstract":"The Arctic LCC has developed a Project Tracking System(PTS) to assist with the management of projects. The PTS is used to track projects throughout all stages of development, from receipt of proposals through delivery of final products.",
    "status":"onGoing",
    "language":[
      "eng; USA",
      "spa; Spanish; Castilian"
    ],
    "purpose":"The LAS files can be used to create DEMs and also to extract topographic data in software that does not support raster data. Other surface features can also be extracted with custom applications. LiDAR data has a wide range of uses such as earthquake hazard studies, hydrologic modeling, forestry, coastal engineering, roadway and pipeline engineering, flood plain mapping, wetland studies, geologic studies and a variety of analytical and cartographic projects.",
    "credit":[
      "FEMA",
      "Washington DNR and Lewis County",
      "Puget Sound LiDAR Consortium (PSLC) - The PSLC is supported by the Puget Sound Regional Council, the National Aeronautical and Space Administration (NASA), the United States Geological Survey (USGS) and numerous partners in local, state, and tribal government."
    ],
    "spatialRepresentation":[
      "textTable",
      "grid",
      "tin"
    ],
    "topicCategory":[
      "boundaries",
      "environment",
      "climatologyMeteorologyAtmosphere"
    ],
    "environmentDescription":"Processed datafiles created in a Windows 7 environment, using R x64 2.15.1, Kepler 2.3, pgAdminIII and Postgres 9.1, and ArcInfo 10.2",
    "supplementalInfo":"A footprint of this data set may be viewed in Google Earth at: <ftp://ftp.csc.noaa.gov/pub/crs/beachmap/qa_docs/wa/pslc2012/wa2012_pslc_chehalis_footprint.KMZ> A Lidar Report from the vendor for this data set may be viewed here: <ftp://ftp.csc.noaa.gov/pub/crs/beachmap/qa_docs/wa/pslc2012/wa2012_pslc_chehalis_lidarreport.pdf>",
    "resourceNativeFormat":[
      {
        "formatName":"ExtJS",
        "version":"4.0.7"
      },
      {
        "formatName":"PostgreSQL",
        "version":"9.1"
      },
      {
        "formatName":"PHP",
        "version":"5.3"
      }
    ],
    "resourceMaintenance":[
      {
        "maintenanceFrequency":"fortnightly"
      },
      {
        "maintenanceFrequency":"annually",
        "maintenanceNote":[
          "Updates to data are generally in available November after the season's field data has been validated"
        ]
      },
      {
        "maintenanceNote":[
          "Test of missing frequency code"
        ]
      }
    ],
    "resourceSpecificUsage":[
      {
        "specificUsage":"Developed for land use planning.",
        "userDeterminedLimitation":"Not suitable for use for navigation.",
        "userContactInfo":[
          {
            "contactId":"3",
            "role":"publisher"
          },
          {
            "contactId":"3",
            "role":"author"
          }
        ]
      },
      {
        "specificUsage":"Bathymetry datasets developed for modeling physical oceanographic conditions in the Barrow Straight.",
        "userContactInfo":[
          {
            "contactId":"1",
            "role":"custodian"
          }
        ]
      }
    ],
    "graphicOverview":[
      {
        "fileName":"allRecs_callCounts_bowhead_2010.jpg",
        "fileDescription":"This image is a spectraplot visualizing the density of Bowhead whale calls in the Northeast Chukchi Sea, AMAR recorder locations, and industry lease areas.",
        "fileType":"JPEG",
        "fileLink":"http://aoos.org/aoos-data-resources/bowhead_images2010_0114.jpg"
      },
      {
        "fileName":"cross_section_perc_sommer_2010.png",
        "fileDescription":"."
      },
      {
        "fileName":"pln40_perc_2010_01.png",
        "fileType":"PNG"
      },
      {
        "fileName":"pln40_spec_summer_2010.png"
      }
    ],
    "constraint":{
      "useLimitations":[
        "not for suitable for navigation",
        "draft version",
        "not intended for general use",
        "don't be a jerk"
      ],
      "legalConstraint":[
        {
          "accessConstraint":[
            "patentPending",
            "restricted"
          ],
          "useConstraint":[
            "restricted"
          ],
          "otherConstraint":[
            "Legally barred from use for navigation."
          ]
        },
        {
          "accessConstraint":[
            "otherRestrictions"
          ],
          "useConstraint":[
            "otherRestrictions"
          ],
          "otherConstraint":[
            "Access Constraint: No one else. Use Constraint: None"
          ]
        },
        {
          "accessConstraint":[
            "copyright",
            "patent",
            "patentPending",
            "trademark",
            "license",
            "intellectualPropertyRights",
            "restricted",
            "otherRestrictions"
          ]
        }
      ],
      "securityConstraint":[
        {
          "classification":"unclassified",
          "userNote":"security clearance not required",
          "classificationSystem":"none",
          "handlingDescription":"this is how to handle things..."
        },
        {
          "classification":"intellectualPropertyRights"
        },
        {
          "classification":"secret",
          "userNote":"shhhhh"
        }
      ]
    },
    "taxonomy":{
      "classificationSystem":[
        {
          "title":"Otter Record Survey",
          "date":[
            {
              "date":"2000",
              "dateType":"publication"
            }
          ],
          "responsibleParty":[
            {
              "contactId":"2",
              "role":"publisher"
            }
          ]
        }
      ],
      "taxonGeneralScope":"The otters observed were identified to the subspecies criterion and identified as southern sea otters.",
      "observer":[
        {
          "contactId":"1",
          "role":"principalInvestigator"
        },
        {
          "contactId":"2",
          "role":"pointOfContact"
        }
      ],
      "taxonomicProcedure":"volunteers observed sea otters using binoculars in pairs",
      "voucher":{
        "specimen":"weathered skull found on beach",
        "repository":{
          "contactId":"2",
          "role":"publisher"
        }
      },
      "taxonClass":[
        {
          "taxonRank":"Kingdom",
          "taxonValue":"Animalia"
        },
        {
          "taxonRank":"Phylum",
          "taxonValue":"Chordata"
        },
        {
          "taxonRank":"Subphylum",
          "taxonValue":"Vertebrata"
        },
        {
          "taxonRank":"Class",
