=== dwyl/learn-json-schema/schemas/schema/schema/taxonomy.json
{
  "id": "taxonomy.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Information on the taxa (1 or more) included in the data set, including keywords, taxonomic system and coverage information, and taxonomic classification system.",
  "example": "../../examples/full_example.json#/metadata/resourceInfo/taxonomy",
  "translation": {
    "ISO 19115-2": ["MD_TaxonSys"],
    "FGDC CSDGM": ["idinfo > taxonomy"]
  },
  "required": ["classificationSystem", "taxonomicProcedure", "taxonClass"],
  "additionalProperties": true,
  "properties": {
    "classificationSystem": {
      "type": "array",
      "description": "Information (citation) about the taxonomic classification system or authority used.",
      "translation": {
        "ISO 19115-2": ["MD_TaxonSys > classSys > CI_Citation"],
        "FGDC CSDGM": ["idinfo > taxonomy > taxonsys > classsys"]
      },
      "minItems": 1,
      "items": {
        "$ref": "citation.json"
      }
    },
    "taxonGeneralScope": {
      "type": "string",
      "description": "Description of the range of taxa addressed in the data set or collection. For example, \"all vascular plants were identified to family or species, mosses and lichens were identified as moss or lichen\".",
      "translation": {
        "ISO 19115-2": ["MD_TaxonSys > taxongen"]
      }
    },
    "observer": {
      "type": "array",
      "description": "Information about the individual(s) responsible for the identification(s) of the specimens or sightings. etc.",
      "translation": {
        "ISO 19115-2": ["MD_TaxonSys > obs > CI_ResponsibleParty"]
      },
      "items": {
        "$ref": "contact.json#/definitions/contactRef"
      }
    },
    "taxonomicProcedure": {
      "type": "string",
      "description": "Description of the methods used for taxonomic identification. Could include specimen processing, comparison with museum materials, keys, and key characters, chemical or genetic analyses, etc.",
      "translation": {
        "ISO 19115-2": ["MD_TaxonSys > taxonpro"],
        "FGDC CSDGM": ["idinfo > taxonomy > taxonsys > taxonpro"]
      }
    },
    "voucher": {
      "type": "object",
      "description": "Information on the types of specimen, the repository, and the individuals who identified the vouchers.",
      "example": "../../examples/full_example.json#/metadata/resourceInfo/taxonomy",
      "translation": {
        "ISO 19115-2": ["MD_TaxonSys > voucher > MD_Vouchers"],
        "FGDC CSDGM": ["idinfo > taxonomy > taxonsys > vouchers"]
      },
      "required": ["specimen", "repository"],
      "properties": {
        "specimen": {
          "type": "string",
          "description": "Word or phrase describing the type of specimen collected (e.g. 'herbarium specimens', 'blood samples', 'photographs', 'individuals', or 'batches').",
          "translation": {
            "ISO 19115-2": ["MD_Vouchers > specimen"],
            "FGDC CSDGM": ["idinfo > taxonomy > taxonsys > vouchers > specimens"]
          }
        },
        "repository": {
          "description": "Information about the curator or contact person and/or agency responsible for the specimens.",
          "example": "../../examples/full_example.json#/metadata/resourceInfo/taxonomy/voucher",
          "translation": {
            "ISO 19115-2": ["MD_Vouchers > reposit > CI_ResponsibleParty"],
            "FGDC CSDGM": ["idinfo > taxonomy > taxonsys > vouchers > reposit"]
          },
          "$ref": "contact.json#/definitions/contactRef"
        }
      }
    },
    "taxonClass": {
      "type": "array",
      "description": "Information about the range of taxa addressed in the data set or collection. It is recommended that one provide information starting from the taxonomic rank of kingdom, to a level which reflects the data set or collection being documented. The levels of Kingdom, Division/Phylum, class, Order, Family, Genus, and Species should be included as ranks as appropriate.",
      "translation": {
        "ISO 19115-2": ["MD_TaxonSys > taxonCl > MD_TaxonCl"],
        "FGDC CSDGM": ["idinfo > taxonomy > taxoncl"]
      },
      "minItems": 1,
      "items": {
        "type": "object",
        "example": "../../examples/full_example.json#/metadata/resourceInfo/taxonomy",
        "required": ["taxonRank", "taxonValue"],
        "additionalProperties": true,
        "properties": {
          "taxonRank": {
            "type": "string",
            "description": "Name of the taxonomic rank for which the taxonValue is provided. Example: \"Kingdom\", \"Division\", \"Phylum\", \"Subphylum\", \"SuperClass\", \"Class\", \"SubClass\", \"InfraClass\", \"Superorder\", \"Order\", \"Suborder\", \"Infraorder\", \"Superfamily\", \"Family\", \"Subfamily\", \"Tribe\", \"Subtribe\", \"Genus\", \"Species\".",
            "translation": {
              "ISO 19115-2": [" MD_TaxonCl > taxonrn"],
              "FGDC CSDGM": ["idinfo > taxonomy > taxoncl > taxonrn"]
            }
          },
          "taxonValue": {
            "type": "string",
            "description": "Taxonomic rank value of the taxon being described.",
            "translation": {
              "ISO 19115-2": ["MD_TaxonCl > taxonrv"],
              "FGDC CSDGM": ["idinfo > taxonomy > taxoncl > taxonrv"]
            }
          },
          "common": {
            "type": "string",
            "description": "Specification of applicable common names. These common names may be general descriptions of a group of organisms if appropriate (e.g. insects, vertebrate, grasses, waterfowl, vascular plants, etc.).",
            "translation": {
              "ISO 19115-2": ["MD_TaxonCl > common"],
              "FGDC CSDGM": ["idinfo > taxonomy > taxoncl > common"]
            }
          }
        }
      }
    }
  }
}

=== dwyl/learn-json-schema/schemas/examples/taxonomy.json
[
  {
    "classificationSystem": [
      {
        "title": "title1",
        "date": [
          {
            "date": "1111-11-11",
            "dateType": "dateType11"
          }, {
            "date": "1112-11-11",
            "dateType": "dateType12"
          }
        ],
        "edition": "edition",
        "responsibleParty": [
          {
            "contactId": "contactId11",
            "role": "role11"
          }, {
            "contactId": "contactId12",
            "role": "role12"
          }
        ],
        "presentationForm": ["presentationForm11", "presentationForm12"],
        "identifier": [
          {
            "identifier": "identifier111",
            "type": "type111",
            "authority": {
              "title": "title111",
              "date": [
                {
                  "date": "1111-11-11",
                  "dateType": "dateType111"
                }
              ],
              "responsibleParty": [
                {
                  "contactId": "contactId111",
                  "role": "role111"
                }
              ],
              "onlineResource": [
                {
                  "uri": "http://thisisanexample111.com",
                  "protocol": "protocol111",
                  "name": "name111",
                  "description": "description111",
                  "function": "function111"
                }
              ]
            }
          }
        ],
        "onlineResource": [
          {
            "uri": "http://thisisanexample11.com",
            "protocol": "protocol11",
            "name": "name11",
            "description": "description11",
            "function": "function11"
          }, {
            "uri": "http://thisisanexample12.com",
            "protocol": "protocol12",
            "name": "name12",
            "description": "description12",
            "function": "function12"
          }
        ]
      }
    ],
    "taxonGeneralScope": "taxonGeneralScope1",
    "observer": [
      {
        "contactId": "contactId11",
        "role": "role11"
      }, {
        "contactId": "contactId12",
        "role": "role12"
      }
    ],
    "taxonomicProcedure": "taxonomicProcedure1",
    "voucher": {
      "specimen": "specimen1",
      "repository": {
        "contactId": "contactId1",
        "role": "role1"
      }
    },
    "taxonClass": [
      {
        "common": "common11",
        "taxonRank": "taxonRank11",
        "taxonValue": "taxonValue11"
      }, {
        "common": "common12",
        "taxonRank": "taxonRank12",
        "taxonValue": "taxonValue12"
      }
    ]
  }, {
    "classificationSystem": [
      {
        "title": "Otter Record Survey",
        "date": [
          {
            "date": "2000",
            "dateType": "publication"
          }
        ],
        "responsibleParty": [
          {
            "contactId": "2",
            "role": "publisher"
          }
        ]
      }, {
        "title": "Another Record Survey",
        "date": [
          {
            "date": "2003",
            "dateType": "publication"
          }
        ],
        "responsibleParty": [
          {
            "contactId": "1",
            "role": "publisher"
          }
        ]
      }
    ],
    "taxonGeneralScope": "The otters observed were identified to the subspecies criterion and identified as southern sea otters.",
    "observer": [
      {
        "contactId": "1",
        "role": "principalInvestigator"
      }, {
        "contactId": "2",
        "role": "pointOfContact"
      }
    ],
    "taxonomicProcedure": "volunteers observed sea otters using binoculars in pairs",
    "voucher": {
      "specimen": "weathered skull found on beach",
      "repository": {
        "contactId": "2",
        "role": "publisher"
      }
    },
    "taxonClass": [
      {
        "taxonRank": "Kingdom",
        "taxonValue": "Animalia"
      }, {
        "taxonRank": "Phylum",
        "taxonValue": "Chordata"
      }, {
        "taxonRank": "Subphylum",
        "taxonValue": "Vertebrata"
      }, {
        "taxonRank": "Class",
        "taxonValue": "Mammalia"
      }, {
        "taxonRank": "Subclass",
        "taxonValue": "Theria"
      }, {
        "taxonRank": "Infraclass",
        "taxonValue": "Eutheria"
      }, {
        "taxonRank": "Order",
        "taxonValue": "Carnivora"
      }, {
        "taxonRank": "Suborder",
        "taxonValue": "Caniformia"
      }, {
        "taxonRank": "Family",
        "taxonValue": "Mustilidae"
      }, {
        "taxonRank": "Subfamily",
        "taxonValue": "Lutrinae"
      }, {
        "taxonRank": "Genus",
        "taxonValue": "Enhydra"
      }, {
        "common": "Sea Otter",
        "taxonRank": "Species",
        "taxonValue": "Enhydra lutris"
      }, {
        "common": "Southern Sea Otter",
        "taxonRank": "Subspecies",
        "taxonValue": "Enhydra"
      }
    ]
  }
]
