=== dwyl/learn-json-schema/schemas/schema/schema.json
{
  "id": "schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "1.1.3",
  "description": "schema for ADIwg mdJSON metadata",
  "type": "object",
  "required": ["version", "contact", "metadata"],
  "properties": {
    "version": {
      "type": "object",
      "description": "Identifies the version of the JSON schema standard that applies to the metadata.",
      "example": "../examples/full_example.json#/version",
      "required": ["name", "version"],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "example": "../examples/full_example.json#/version",
          "description": "Schema identifier, i.e. the name of the schema standard."
        },
        "version": {
          "type": "string",
          "example": "../examples/full_example.json#/version",
          "description": "Specific version number of the schema standard.",
          "pattern": "[0-9]\\.[0-9]\\.[0-9]"
        }
      }
    },
    "contact": {
      "$ref": "schema/contact.json"
    },
    "metadata": {
      "$ref": "schema/metadata.json"
    },
    "dataDictionary": {
      "type": "array",
      "description": "A description of the contents, format and structure of the physical objects in a data resource.",
      "translation": {
        "ISO 19115-2": ["FC_FeatureCatalogue"]
      },
      "example": "../examples/full_example.json#/dataDictionary",
      "items": {
        "$ref": "schema/dataDictionary.json"
      }
    }
  },
  "definitions": {
    "url": {
      "type": "string",
      "pattern": "(https?|ftp):\\/\\/(-\\.)?([^\\s\\/?\\.#-]+\\.?)+(\\/[^\\s]*)?$"
    },
    "uri": {
      "type": "string",
      "description": "Location (address) for on-line access using a Uniform Resource Identifier, usually in the form of a Uniform Resource Locator (URL).",
      "example": "../examples/uri.json",
      "translation": {
        "ISO 19115-2": ["CI_OnlineResource > linkage"]
      },
      "pattern": "([A-Za-z][A-Za-z0-9+\\-.]*):(?:(//)(?:((?:[A-Za-z0-9\\-._~!$&'()*+,;=:]|%[0-9A-Fa-f]{2})*)@)?((?:\\[(?:(?:(?:(?:[0-9A-Fa-f]{1,4}:){6}|::(?:[0-9A-Fa-f]{1,4}:){5}|(?:[0-9A-Fa-f]{1,4})?::(?:[0-9A-Fa-f]{1,4}:){4}|(?:(?:[0-9A-Fa-f]{1,4}:){0,1}[0-9A-Fa-f]{1,4})?::(?:[0-9A-Fa-f]{1,4}:){3}|(?:(?:[0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})?::(?:[0-9A-Fa-f]{1,4}:){2}|(?:(?:[0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})?::[0-9A-Fa-f]{1,4}:|(?:(?:[0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})?::)(?:[0-9A-Fa-f]{1,4}:[0-9A-Fa-f]{1,4}|(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))|(?:(?:[0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})?::[0-9A-Fa-f]{1,4}|(?:(?:[0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})?::)|[Vv][0-9A-Fa-f]+\\.[A-Za-z0-9\\-._~!$&'()*+,;=:]+)\\]|(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|(?:[A-Za-z0-9\\-._~!$&'()*+,;=]|%[0-9A-Fa-f]{2})*))(?::([0-9]*))?((?:/(?:[A-Za-z0-9\\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})*)*)|/((?:(?:[A-Za-z0-9\\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})+(?:/(?:[A-Za-z0-9\\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})*)*)?)|((?:[A-Za-z0-9\\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})+(?:/(?:[A-Za-z0-9\\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})*)*)|)(?:\\?((?:[A-Za-z0-9\\-._~!$&'()*+,;=:@/?]|%[0-9A-Fa-f]{2})*))?(?:\\#((?:[A-Za-z0-9\\-._~!$&'()*+,;=:@/?]|%[0-9A-Fa-f]{2})*))?"
    },
    "date": {
      "type": "string",
      "description": "An ISO 8601 date/timestamp.",
      "example": "../examples/date.json",
      "pattern": "^(\\d{4}(-\\d{2})?(-\\d{2})?$)|(^\\d{4}-\\d{2}-\\d{2}(T\\d{2})?(\\:\\d{2}(\\:\\d{2}(\\.\\d+)?)?|Z)?(Z|(-|\\+)\\d{2}(:\\d{2})?)?$)"
    }
  }
}

=== dwyl/learn-json-schema/schemas/examples/full_example.json
{
  "version":{
    "name":"mdJson",
    "version":"1.1.0"
  },
  "contact":[
    {
      "contactId":"1",
      "organizationName":"US Geological Survey - Alaska Science Center",
      "primaryRole": "owner",
      "onlineResource":[
        {
          "uri":"http://alaska.usgs.gov/",
          "protocol":"http",
          "name":"Alaska Science Center Home Page",
          "description":"Alaska Science Center home page",
          "function":"information"
        }
      ],
      "contactInstructions":"Complete Department and Employee phone book online with email addresses",
      "phoneBook":[
        {
          "phoneName":"Main Phone",
          "phoneNumber":"907-786-7000",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"Main Fax",
          "phoneNumber":"907-786-7020",
          "service":[
            "fax"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "4210 University Drive"
        ],
        "city":"Anchorage",
        "administrativeArea":"AK",
        "postalCode":"99508",
        "country":"USA"
      }
    },
    {
      "contactId":"2",
      "individualName":"Urban, Frank",
      "organizationName":"US Geological Survey",
      "positionName":"Research Geologist",
      "primaryRole": "principleInvestigator",          
      "onlineResource":[
        {
          "uri":"http://academic.research.microsoft.com/Author/27724864/frank-e-urban",
          "protocol":"http",
          "name":"Microsoft Academic Search",
          "description":"Academic publications of Frank Urban",
          "function":"information"
        },
        {
          "uri":"http://www.linkedin.com/pub/frank-urban/27/565/1a8",
          "protocol":"http",
          "name":"LinkedIn",
          "description":"Frank Urban's Linked In page",
          "function":"information"
        },
        {
          "uri":"http://data.usgs.gov/climateMonitoring/region/show?region=alaska"
        }
      ],
      "contactInstructions":"Leave a message if no answer.",
      "phoneBook":[
        {
          "phoneName":"office",
          "phoneNumber":"303-236-5953",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"mobile",
          "phoneNumber":"808-236-5463",
          "service":[
            "voice",
            "sms"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "West 6th Ave. & Kipling St.",
          "DFC Bldg. 810"
        ],
        "city":"Lakewood",
        "administrativeArea":"CO",
        "postalCode":"80225",
        "country":"USA",
        "electronicMailAddress":[
          "furban@usgs.gov"
        ]
      }
    },
    {
      "contactId":"3",
      "organizationName":"US Geological Survey - Permafrost and Climate Monitoring",
      "onlineResource":[
        {
          "uri":"http://data.usgs.gov/climateMonitoring/region/show?region=alaska",
          "protocol":"http",
          "name":"Real-Time Permafrost and Climate Monitoring Network - Arctic Alaska",
          "description":"",
          "function":"information"
        }
      ],
      "phoneBook":[
        {
          "phoneName":"main office",
          "phoneNumber":"303-236-5900",
          "service":[
            "voice"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "West 6th Ave. & Kipling St.",
          "DFC Bldg. 810"
        ],
        "city":"Lakewood",
        "administrativeArea":"CO",
        "postalCode":"80225",
        "country":"USA",
        "electronicMailAddress":[
          "pcm_info@usgs.gov"
        ]
      }
    },
    {
      "contactId":"4",
      "organizationName":"FWS - Arctic National Wildlife Refuge",
      "onlineResource":[
        {
          "uri":"http://www.fws.gov/alaska/nwr/arctic/",
          "name":"Arctic National Wildlife Refuge",
          "description":"Arctic National Wildlife Refuge home page",
          "function":"information"
        }
      ],
      "phoneBook":[
        {
          "phoneName":"main office",
          "phoneNumber":"907-456-0250",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"main office toll free",
          "phoneNumber":"800-362-4546",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"main office",
          "phoneNumber":"907-456-0428",
          "service":[
            "fax"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "101 12th Avenue",
          "Room 236"
        ],
        "city":"Fairbanks",
        "administrativeArea":"AK",
        "postalCode":"99701",
        "country":"USA",
        "electronicMailAddress":[
          "arctic_refuge@fws.gov"
        ]
      }
    },
    {
      "contactId":"5",
      "individualName":"",
      "organizationName":"BLM - Arctic Field Office",
      "onlineResource":[
        {
          "uri":"http://www.blm.gov/ak/st/en/fo/fdo/arctic_field_office.html",
          "name":"Bureau of Land Management - Alaska",
          "description":"Arctic Field office home page",
          "function":"information"
        }
      ],
      "contactInstructions":"Please send comments and questions about the BLM and its programs to woinfo@blm.gov",
      "phoneBook":[
        {
          "phoneName":"main office",
          "phoneNumber":"907-474-2200",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"main office toll free",
          "phoneNumber":"800-437-7021",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"main office",
          "phoneNumber":"907-474-2280",
          "service":[
            "fax"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "1150 University Avenue"
        ],
        "city":"Fairbanks",
        "administrativeArea":"AK",
        "postalCode":"99709",
        "country":"USA",
        "electronicMailAddress":[
          "Arctic@blm.gov",
          "woinfo@blm.gov"
        ]
      }
    },
    {
      "contactId":"6",
      "individualName":"Clow, Gary D.",
      "organizationName":"US Geological Survey",
      "positionName":"Research Geophysicist",
      "phoneBook":[
        {
          "phoneName":"office",
          "phoneNumber":"303-236-5944",
          "service":[
            "voice"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "West 6th Ave. & Kipling St.",
          "DFC Bldg. 810",
          "Building 25"
        ],
        "city":"Lakewood",
        "administrativeArea":"CO",
        "postalCode":"80225",
        "country":"USA",
        "electronicMailAddress":[
          "gclow@usgs.gov",
          "gary.clow@colorado.edu"
        ]
      }
    },
    {
      "contactId":"7",
      "individualName":"Brown, A.C.",
      "organizationName":"US Geological Survey - Alaska Science Center",
      "positionName":"Metadata Specialist",
      "phoneBook":[
        {
          "phoneName":"office",
          "phoneNumber":"907-786-7002",
          "service":[
            "voice"
          ]
        },
        {
          "phoneName":"main office",
          "phoneNumber":"907-786-7040",
          "service":[
            "fax"
          ]
        }
      ],
      "address":{
        "deliveryPoint":[
          "4230 University Drive",
          "Suite 201"
        ],
        "city":"Anchorage",
        "administrativeArea":"AK",
        "postalCode":"99508",
        "country":"USA",
        "electronicMailAddress":[
          "acbrown2@usgs.gov"
        ]
      }
    },
    {
      "contactId":"8",
      "individualName":"Sharon Smith",
      "organizationName":"Global Terrestrial Network for Permafrost (GTN-P)",
      "positionName":"Permafrost Research Scientist ",
      "onlineResource":[
        {
          "uri":"http://www.gtnp.org/",
          "protocol":"http",
          "name":"Global Terrestrial Network for Permafrost",
          "description":"Home page for the network initiative",
          "function":"information"
        }
      ],
      "contactInstructions":"email preferred",
      "phoneBook":[
        {
          "phoneName":"Office",
          "phoneNumber":"(613) 947-7066",
          "service":[
            "voice",
            "fax"
          ]
        }
      ],
      "address":{
        "electronicMailAddress":[
          "permafrost@nrcan.gc.ca"
        ]
      }
    },
    {
      "contactId":"9",
      "organizationName":"U.S. National Science Foundation, Division of Polar Programs, Directorate for Geosciences",
      "onlineResource":[
        {
          "uri":"http://www.nsf.gov",
          "protocol":"http",
          "name":"U.S.  National Science Foundation",
          "description":"Home page for the agency",
          "function":"information"
        }
      ]
    }
  ],
  "metadata":{
    "metadataInfo":{
      "metadataIdentifier":{
        "identifier":"D5D16D06-CEEB-E011-8260-000C2952247E",
        "type":"uuid"
      },
      "parentMetadata":{
        "title":"Changing Arctic Ecosystems Initiative (CAE)",
        "date":[
          {
            "date":"2011-09-14",
            "dateType":"publication"
          }
        ],
        "identifier":[
          {
            "identifier":"D5B16D06-CFEB-E011-8260-000C2952247E",
            "type":"uuid"
          },
          {
            "identifier":"ALCC2018-99",
            "type":"project"
          }
        ],
        "responsibleParty":[
          {
            "contactId":"1",
            "role":"pointOfContact"
          }
        ],
        "presentationForm":[
          "documentDigital"
        ],
        "onlineResource":[
          {
            "uri":"http://alaska.usgs.gov/rex/adiwg/public/projects/316?format=xml",
            "protocol":"http",
            "description":"Project metadata record for CAE"
